[platformio]

[env]
board = lilygo-t-display-s3
board_build.arduino.memory_type = dio_opi ; NEEDED FOR PSRAM
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
platform_packages =
    platformio/framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.1
    platformio/framework-arduinoespressif32-libs@https://dl.espressif.com/AE/esp-arduino-libs/esp32-3.1.1-h.zip
framework = arduino
monitor_speed = 115200
lib_deps =
        adafruit/Adafruit SSD1306@^2.5.9
        adafruit/Adafruit NeoPixel@^1.12.3
        adafruit/Adafruit GFX Library@^1.11.11
        mikalhart/TinyGPSPlus@^1.0.3
        mathieucarbou/ESPAsyncWebServer@^3.4.0
        mathieucarbou/AsyncTCP@^3.2.7


[env:nodemcu-32s3-dev]
extends = env
build_flags =
    ${common.build_flags}
    -D DEV=1
    -Iapp
build_src_filter = +<*> +<../app/*>
board_build.filesystem = littlefs
board_build.partitions = default.csv


[common]
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1