name = "gps-tracker" # Hoặc tên dự án của bạn
main = "worker.js"   # Đường dẫn tới file code của bạn
compatibility_date = "2026-01-01"

[[kv_namespaces]]
binding = "TRACKER_KV"
id = "7233e95725d346a988fc6ba69c2ddec9"