export {
  initAnalytics,
  trackPageView,
  trackSectionView,
  trackNavbarClick,
  trackCTA,
  trackDeviceSelected,
  trackSearch,
  trackSearchResultClick,
  trackHistoryRangeChange,
  trackRouteModeChange,
  trackMapLayerChange,
  trackFetchCurrentLocation,
  trackRenameDevice,
  trackHomePickStart,
  trackHomeSaved,
  trackHomeCleared,
  trackSidebarToggle,
  trackThemeChange,
  trackLanguageChange,
  trackOrderFormStart,
  trackOrderFormSubmit,
  trackOrderFormSuccess,
  trackOrderFormError,
  trackContactClick,
  trackApiError,
  trackApiRequest,
} from "./webAnalytics";